### ISSUE TITLE
Move away from string interpolation & adopt query parameters

### ISSUE THREAD

**Issue by intoverflow** [ambertide/datalite#6]
The current implementation uses string interpolation to construct sqlite queries.

See the following for a typical example:

https://github.com/ambertide/datalite/blob/81010fc015fbd8cba12ba86b27e4e88b8b79c179/datalite/datalite_decorator.py#L30

This causes problems when trying to insert JSON data (or other fancy strings) into a table.

There is another way to pass values into queries: so-called query parameters. Query parameters do not have this same limitation. See [cursor-objects (sqlite3)](https://docs.python.org/3/library/sqlite3.html#cursor-objects).

**Comment by ambertide** [comment]
I also made certain changes that further adopt query parameters where I could to hopefully protect against SQL injections, I think it is in a good state right now.
